### ISSUE TITLE
Major release and Zenodo DOI.

### ISSUE THREAD

**Issue by tsalo** [NBCLab/abbr#23]
Make abbr citable.

**Comment by emdupre** [comment]
GitHub has an official [guide](https://guides.github.com/activities/citable-code/)!

**Comment by tsalo** [comment]
We'll need a major release before we put it on zenodo. It'll be a good opportunity for us to learn about [semantic versioning](http://semver.org), and maybe even push this to pypi. There are some instructions for the latter [here](http://peterdowns.com/posts/first-time-with-pypi.html).

What, if anything, do you want to get done for `1.0.0`?

**Comment by emdupre** [comment]
I'd definitely like to get it onto pypi for this release. What were you thinking?

**Comment by tsalo** [comment]
Maybe just increase coverage a bit. I was thinking we could get to 100% and then do the release.
