### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by tongmeihan1995** [NBCLab/abbr#27]
Permission denied (publickey).
fatal: Could not read from remote repository

**Comment by tsalo** [comment]
Could you provide a bit more information about this issue, like what you were trying to do and what specific command you used?

**Comment by LAOKE1997** [comment]
when i want to install, it says:"
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
"
Could you please help with it?

**Comment by tsalo** [comment]
Based on the error message, I think you don't have GitHub set up as a valid SSH host. You could either set it up (see [here](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)) or download the repository as a zip folder to your local machine (see the screen shot below). 

Does that help?

![image](https://user-images.githubusercontent.com/8228902/117587904-33a3a600-b0ee-11eb-8cf6-312162b4d1fd.png)

**Comment by LAOKE1997** [comment]
OK THX!
